name: .NET Framework CI/CD

on:
  push:
    branches:
      - main  # Trigger the workflow when there is a push to the main branch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET Framework SDK
      uses: microsoft/setup-dotnet@v1
      with:
        dotnet-version: '4.8'  # Use the version matching your app

    - name: Restore dependencies
      run: nuget restore GithubProject.sln

    - name: Build application
      run: msbuild GithubProject.sln /p:Configuration=Release

    - name: Publish application
      run: |
        mkdir -p ./publish
        msbuild GithubProject.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile /p:PublishDir=./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: gitHubDeployment
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ./publish

          
